[package]
name = "engine"
edition = "2021"
rust-version = "1.88"
edition = "2021"

[features]
default = ["web"]
web = ["wgpu/web"]

[dependencies]
wgpu = { version = "27.0.0", features = [
    "custom",
    "wgsl",
], default-features = false }
pollster = { version = "0.4", features = ["macro"] }