[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../engine" }
imgui = "0.12"
imgui-rs-vulkan-renderer = "1.16.0"
imgui-winit-support = "0.12.0"
anyhow = "1.0"
winit = "0.29"
ash = "0.38"